version: "3.9"

services:
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: "http://172.25.8.241:3000"
    restart: always
